### ISSUE TITLE
Broken in latest VSCode

### ISSUE THREAD

**Issue by alex-dixon** [alex-dixon/vscode-typescript-repl#15]
```
TypeError: Value of "this" must be of type nullish or must be the global object
    at new NodeError (node:internal/errors:406:5)
    at Object.cryptoThisCheck (node:internal/process/pre_execution:334:17)
    at Object.get crypto [as crypto] (node:internal/util:649:9)
    at Function.assign (<anonymous>)
    at evaluate (/Users/alexdixon/.cursor/extensions/alexdixon.vscode-typescript-repl-0.0.5-alpha.0/dist/index.js:1251:35)
    at /Users/alexdixon/.cursor/extensions/alexdixon.vscode-typescript-repl-0.0.5-alpha.0/dist/index.js:1381:28
    at f.h (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:206663)
    at f.$executeContributedCommand (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:207523)
    at R.S (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:5996)
    at R.Q (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:5762)
    at R.M (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:4782)
    at R.L (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:3606)
    at c.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:2298)
    at i.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:739)
    at i.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:956)
    at d.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:14576)
    at c.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:186:8651)
    at i.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:739)
    at i.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:956)
    at d.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:14576)
    at MessagePortMain.<anonymous> (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:186:6777)
    at MessagePortMain.emit (node:events:514:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285) {
  code: 'ERR_INVALID_THIS',
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}
  ]
}
```

https://github.com/nodejs/node/pull/45857/files

not sure what the deal is yet. stacktrace references approxmiately a call to vm.runInContext with the context that is supposed to be a clone of the current "base" programming environment (node globals etc).

Maybe we need a .bind(global) in assignGlobal for the crypto module...?

**Comment by alex-dixon** [comment]
fixed and published as 0.0.6
